import { NavbarSimple } from "../components/Navbar";

import Footer from "../components/Footer";

export const metadata = {
  title: "JQueen Property",
  description: "Generated by create next app",
};
export default function Layout({ children }) {
  return (
    <div>
      <main className="flex flex-col  justify-between">
        <NavbarSimple />
        {children}
      </main>
      <Footer />
    </div>
  );
}
